# Copyright 2023 - TODAY, Akretion - Raphael Valyi <raphael.valyi@akretion.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/sped-extractor and xsdata-odoo

from odoo import api, fields, models

# Guia Prático, C100, Exceção 1: no child register under these situations.
COD_SIT_WITHOUT_CHILDREN = ("02", "03", "04", "05")


class SpecMixinEFDICMSIPI(models.AbstractModel):
    _name = "l10n_br_sped.mixin.efd_icms_ipi"
    _description = "l10n_br_sped.mixin.efd_icms_ipi"
    _inherit = "l10n_br_sped.mixin"

    declaration_id = fields.Many2one(
        comodel_name="l10n_br_sped.efd_icms_ipi.0000",
        required=True,
        ondelete="cascade",
    )

    state = fields.Selection(related="declaration_id.state")

    @api.model
    def _pull_records_from_odoo(
        self, kind, level, parent_register=None, parent_record=None, log_msg=None
    ):
        # A cancelled, denied or voided document is written as its C100 alone
        # (Guia Prático, C100, Exceção 1): its children are never pulled.
        if (
            parent_register
            and parent_register._name == "l10n_br_sped.efd_icms_ipi.c100"
            and parent_register.COD_SIT in COD_SIT_WITHOUT_CHILDREN
        ):
            return
        return super()._pull_records_from_odoo(
            kind, level, parent_register, parent_record, log_msg
        )

    def _format_field_value(self, field, value):
        # A zero is written only where the layout requires the field
        # (out_required); an optional numeric field is left blank.
        if field.type in ("integer", "float", "monetary") and not value:
            return "0" if getattr(field, "out_required", False) else ""
        if field.type == "monetary" and value % 1:
            # The base writes str(value), with a dot; the SPED decimal
            # separator is the comma, with the two decimals of the layout.
            return f"{value:.2f}".replace(".", ",")
        return super()._format_field_value(field, value)
