# Copyright 2023 - TODAY, Akretion - Raphael Valyi <raphael.valyi@akretion.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/sped-extractor and xsdata-odoo

from odoo import fields, models


class SpecMixinEFDPISCOFINS(models.AbstractModel):
    _name = "l10n_br_sped.mixin.efd_pis_cofins"
    _description = "l10n_br_sped.mixin.efd_pis_cofins"
    _inherit = "l10n_br_sped.mixin"

    declaration_id = fields.Many2one(
        comodel_name="l10n_br_sped.efd_pis_cofins.0000",
        required=True,
        ondelete="cascade",
    )

    state = fields.Selection(related="declaration_id.state")

    def _format_field_value(self, field, value):
        """Formato numérico do leiaute da EFD-Contribuições.

        - Zero só onde o leiaute exige o campo (``out_required`` do spec); um
          campo numérico opcional zerado sai em branco, como o PVA espera.
        - Valor monetário sempre com duas casas e vírgula (Guia Prático 1.35,
          Seção 3, item 3.1: sem separador de milhar, vírgula como separador
          decimal). O ``sped_base`` ainda escreve o monetário com ponto quando
          há centavos ("10.5"), o que o PVA recusa.
        """
        if field.type in ("integer", "float", "monetary") and not value:
            if self.env.context.get("efd_blank_zero"):
                return ""
            if field.name in self.env.context.get("efd_zero_fields", ()):
                return "0"
            return "0" if getattr(field, "out_required", False) else ""
        if field.type == "monetary":
            return f"{value:.2f}".replace(".", ",")
        result = super()._format_field_value(field, value)
        if field.type in ("char", "selection", "text") and result:
            # Guia 1.35, Seção 3, item a: o campo alfanumérico aceita a tabela
            # ASCII exceto o "|" e os caracteres não imprimíveis (0 a 31). Um
            # TAB colado na descrição do produto faz o PGE recusar a
            # importação do arquivo inteiro.
            result = "".join(
                " " if ord(char) < 32 or char == "|" else char for char in result
            ).strip()
        return result
